"""create initial schema

Revision ID: 1ef14c36cb4b
Revises: 
Create Date: 2026-09-11 23:25:59.941262

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ef14c36cb4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('gym_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_days_routine_id'), 'gym_days', ['routine_id'], unique=False)
    op.create_table('exercise_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_day_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('rep_range_low', sa.Integer(), nullable=False),
    sa.Column('rep_range_high', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gym_day_id'], ['gym_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_definitions_gym_day_id'), 'exercise_definitions', ['gym_day_id'], unique=False)
    op.create_table('logged_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_day_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_day_id'], ['gym_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logged_sessions_gym_day_id'), 'logged_sessions', ['gym_day_id'], unique=False)
    op.create_index(op.f('ix_logged_sessions_logged_at'), 'logged_sessions', ['logged_at'], unique=False)
    op.create_table('logged_exercise_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_definition_id', sa.Integer(), nullable=False),
    sa.Column('weight_lb', sa.Float(), nullable=False),
    sa.Column('reps_done', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_definition_id'], ['exercise_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['logged_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'exercise_definition_id', name='uq_session_exercise')
    )
    op.create_index(op.f('ix_logged_exercise_results_exercise_definition_id'), 'logged_exercise_results', ['exercise_definition_id'], unique=False)
    op.create_index(op.f('ix_logged_exercise_results_session_id'), 'logged_exercise_results', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logged_exercise_results_session_id'), table_name='logged_exercise_results')
    op.drop_index(op.f('ix_logged_exercise_results_exercise_definition_id'), table_name='logged_exercise_results')
    op.drop_table('logged_exercise_results')
    op.drop_index(op.f('ix_logged_sessions_logged_at'), table_name='logged_sessions')
    op.drop_index(op.f('ix_logged_sessions_gym_day_id'), table_name='logged_sessions')
    op.drop_table('logged_sessions')
    op.drop_index(op.f('ix_exercise_definitions_gym_day_id'), table_name='exercise_definitions')
    op.drop_table('exercise_definitions')
    op.drop_index(op.f('ix_gym_days_routine_id'), table_name='gym_days')
    op.drop_table('gym_days')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
